cart/urls.py
from django.urls import path,include
from cart import views


app_name ='cart'

urlpatterns = [
    path('',views.cart,name = 'cart'),
    path('add/cart/<int:pk>/',views.addCart,name='addCart'),
    path('update/cart/<int:pk>/',views.updateCart,name='updateCart'),
    path('remove-form-wishlist-to-cart/<int:pk>/',views.wish_to_cart,name='wish_to_cart'),
    path('remove/cart/<int:pk>/',views.removeCart,name = 'removeCart'),
    path('remove-all-cart/',views.removeAllCart,name = 'removeAllCart'),



]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views
from accounting import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/login/', views.redirectToLogin, name='login'),
    path('admin/', admin.site.urls),
    path('account/', include('accounting.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/signup/', TemplateView.as_view(template_name="account/customer/signup.html")),

    path('', include('home.urls')),
    path('profile/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    path('blog/', include('blog.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('faq/', include('faq.urls')),
    path('about/', include('about_us.urls')),
    path('contact/', include('contact.urls')),
    path('checkout/', include('checkout.urls')),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name = "registration/password_reset.html"),name='lost_password'),
    path('accounts/', include('django.contrib.auth.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path,include
from faq import views

app_name ='faq'


urlpatterns = [
        path('',views.faq,name='faq'),

]

home/urls.py
from django.urls import path,include
from home import views

app_name ='home'


urlpatterns = [
    path('', views.homepage,name = 'home'),
    path('product-detail/<int:pk>/',views.product_detail,name= 'product_detail'),
    path('shop-grid-left/<int:pk>/', views.shop_grid_left,name = 'shop_grid_left'),
    path('shop-grid-left/', views.all_shop_grid_left,name = 'all_shop_grid_left'),
    path('shop-grid-left-sub-category/<int:pk>/', views.shop_grid_left_sub_category,name = 'shop_grid_left_sub_category'),
    path('shop-grid-left-category/<int:pk>/', views.shop_grid_left_category,name = 'shop_grid_left_category'),

]

cart/models.py
from django.db import models
from accounting.models import User
from dashboard.models import Address,DefaultAddress,AddressType,Country,State,City,Area,Pincode
from home.models import ProductMainCategory,ProductSubCategory,ProductCategory,MainProduct,Product,Product_SubInformation,Information,ProductTags,ProductPolicy,AvailablePolicies,ProductReview,Product_SubInformation,Information
from wishlist.models import ProductWishList
from datetime import datetime
from datetime import date
# Create your models here.



class ProductCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    Product_cart_Upload_Date = models.DateTimeField(default = datetime.now())
    Product_quantity = models.IntegerField(default=1,)

    def __str__(self):
        return self.product.Product_Title

cart/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.core import serializers
from accounting.models import User
from dashboard.models import Address,DefaultAddress,AddressType,Country,State,City,Area,Pincode
from home.models import ProductMainCategory,ProductSubCategory,ProductCategory,MainProduct,Product,Product_SubInformation,Information,ProductTags,ProductPolicy,AvailablePolicies,ProductReview,Product_SubInformation,Information
from home.forms import ProductUploadForm
from wishlist.models import ProductWishList
from cart.models import ProductCart
from django.contrib import messages
from django.core.files.storage import FileSystemStorage 
from django.contrib.auth.decorators import login_required

# Create your views here.


# @login_required
def cart(request):
    total_amount = 0
    gst = 0
    charge = 0
    grand_total = 0
    
    try:
        for product_price in ProductCart.objects.filter(user = request.user):
            total = product_price.product.Product_Price * product_price.Product_quantity
            total_amount += total
            if product_price.product.ProductShipping == 'charge' :
                if total_amount >= 5000 :
                    charge = 0
                else:
                    charge += 75
            else:
                if total_amount >= 5000 :
                    charge = 0
                else :
                    charge += 0

        gst = total_amount/100*17
        total_amount = total_amount/100*83
        grand_total = charge+total_amount+gst
        ProductCarts = ProductCart.objects.filter(user = request.user)

        if grand_total >= 5000:
            charge = 0
        charges = charge

    except:
        gst={}
        total_amount={}
        grand_total={}
        charges={}
        ProductCarts={}

    # print('charge',charge)
    # print('total_amount',total_amount)
    # print('gst',gst)
    # print('grandtotal',grand_total)
     
    context = {
        'ProductCart' : ProductCarts,
        'charge': charges,
        'total_amount':total_amount,
        'gst': gst,
        'grandtotal':grand_total,
    }
        
    return render(request,'cart/cart.html',context)


    

def addCart(request,pk):
    if request.method == 'POST':
        if request.user.is_authenticated:
            # print(request.POST.get('product_pk'))
            # print(request.POST.get('product_qty'))
            p, created = ProductCart.objects.get_or_create(
                user = User.objects.get(pk = request.user.pk),
                product = Product.objects.get(pk = pk),
                # Product_quantity = request.POST.get('product_qty'),
            )

            p.Product_quantity = request.POST.get('product_qty')
            p.save()

            if created:
                return JsonResponse({'res':'Product :- Added to cart','qty':request.POST.get('product_qty')})
            else:
                return JsonResponse({'res':'Product :- Exist to cart','qty':request.POST.get('product_qty')})
        else:
            return JsonResponse ({'res':'PleaseLogin'})
    
    return render(request,'cart/cart.html')


def updateCart(request,pk):
    if request.method == 'POST':

        p, created = ProductCart.objects.get_or_create(
            user = User.objects.get(pk = request.user.pk),
            product = Product.objects.get(pk = pk),
            # Product_quantity = request.POST.get('product_qty'),
        )

        p.Product_quantity = request.POST.get('product_qty')
        p.save()

        if created:
            return JsonResponse({'qty':request.POST.get('product_qty')})
        else:
            return JsonResponse({'qty':request.POST.get('product_qty')})
    return render(request,'cart/cart.html')


def wish_to_cart(request,pk):
    if request.method == 'GET':
        p, created = ProductCart.objects.get_or_create(
            user = User.objects.get(pk = request.user.pk),
            product = Product.objects.get(pk = pk),
            # Product_quantity = request.POST.get('product_qty'),
        )
        p.Product_quantity = request.GET.get('product_qty')


        obj_deleted = ProductWishList.objects.filter(product__Product_Title = Product.objects.get(pk = pk)).delete()
        # print(obj_deleted)

        if created:
            return redirect('cart:cart')
        else:
            return redirect('cart:cart')

        
    # wishlist_del = ProductWishList.objects.filter(pk=pk)
    # wishlist_del.delete()
    
    return redirect('cart:cart')

def removeCart(request,pk):
    # print(pk)
    ProductCart.objects.filter(pk=pk).delete()
    return redirect('cart:cart')

def removeAllCart(request):
    try:
        ProductCart.objects.filter(user = User.objects.get(pk = request.user.pk)).delete()
    except:
        messages.error(request,f'login first and try it again..' )
    return redirect('cart:cart')

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
<!--====== App Content ======-->
{% block content %}
{% csrf_token %}
<div class="app-content">
  <!--====== Section 1 ======-->
  <div class="u-s-p-y-60">
    <!--====== Section Content ======-->
    <div class="section__content">
      <div class="container">
        <div class="breadcrumb">
          <div class="breadcrumb__wrap">
            <ul class="breadcrumb__list">
              <li class="has-separator">
                <a href="index.html">Home</a>
              </li>
              <li class="is-marked">
                <a href="cart.html">Cart</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--====== End - Section 1 ======-->
  <!--====== Section 2 ======-->
  <div class="u-s-p-b-60">
    <!--====== Section Intro ======-->
    <div class="section__intro u-s-m-b-60">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="section__text-wrap">
              <h1 class="section__heading u-c-secondary">SHOPPING CART</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--====== End - Section Intro ======-->
    <!--====== Section Content ======-->
    <div class="section__content">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 u-s-m-b-30">
            <div class="table-responsive">
              <table class="table-p">
                <tbody>
                  <!--====== Row ======-->
                  {% for ProductCart in ProductCart %}
                  {% if request.user == ProductCart.user %}
                  <tr>
                    <td>
                      <div class="table-p__box">
                        <div class="table-p__img-wrap">
                          <a id="href_get_{{ProductCart.product.pk}}" href="{% url 'cart:updateCart' ProductCart.product.pk  %}" ></a>
                          <img class="u-img-fluid" src="{{ProductCart.product.Product_Img_1.url}}" alt="">
                        </div>
                        <div class="table-p__info">
                          <span class="table-p__name">
                          <a href="{% url 'home:product_detail' ProductCart.product.pk %}">{{ProductCart.product.Product_Title|slice:'0:30'}} ...</a></span>
                          <span class="table-p__category">
                          <a href="{% url 'home:shop_grid_left' ProductCart.product.maincategory.pk %}">{{ProductCart.product.maincategory|title}}</a></span>
                          <ul class="table-p__variant-list">
                            <li>
                              <span>Size: 22</span>
                            </li>
                            <li>
                              <span>Color: Red</span>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </td>
                    <td>
                      <span class="table-p__price get_price_{{ProductCart.product.pk}}" >$ {{ProductCart.product.Product_Price}}</span>
                    </td>
                    <td>
                      <div class="table-p__input-counter-wrap">
                        <!--====== Input Counter ======-->
                        <div class="input-counter">
                          <span id="{{ProductCart.product.pk}}" class="input-counter__minus fas fa-minus ajax_clicked"></span>
                          <input class="input-counter__text input-counter--text-primary-style" name="jquery_qty_{{ProductCart.product.pk}}" type="text" value="{{ProductCart.Product_quantity}}" data-min="1" data-max="1000">
                          <span id="{{ProductCart.product.pk}}" class="input-counter__plus fas fa-plus ajax_clicked"></span>
                        </div>
                        <!--====== End - Input Counter ======-->
                      </div>
                    </td>
                    <td>
                      <div class="table-p__del-wrap">
                        <a class="far fa-trash-alt table-p__delete-link" href="{% url 'cart:removeCart' ProductCart.pk %}"></a>
                      </div>
                    </td>
                  </tr>
                  {% endif %}
                  {% endfor ProductCart %}
                  <!--====== End - Row ======-->
                </tbody>
              </table>
            </div>
          </div>
          <div class="col-lg-12">
            <div class="route-box">
              <div class="route-box__g1">
                <a class="route-box__link" href="{% url 'home:all_shop_grid_left' %}"><i class="fas fa-long-arrow-alt-left"></i>
                <span>CONTINUE SHOPPING</span></a>
              </div>
              <div class="route-box__g2">
                <a class="route-box__link" href="{% url 'cart:removeAllCart' %}"><i class="fas fa-trash"></i>
                <span>CLEAR CART</span></a>
                <a class="route-box__link" href="{% url 'cart:cart' %}"><i class="fas fa-sync"></i>
                <span>UPDATE CART</span></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--====== End - Section Content ======-->
  </div>
  <!--====== End - Section 2 ======-->
  <!--====== Section 3 ======-->
  <div class="u-s-p-b-60">
    <!--====== Section Content ======-->
    <div class="section__content">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 u-s-m-b-30">
            <form class="f-cart">
              <div class="row">
                <div class="col-lg-4 col-md-6 u-s-m-b-30">
                  <div class="f-cart__pad-box">
                    <h1 class="gl-h1">ESTIMATE SHIPPING AND TAXES</h1>
                    <span class="gl-text u-s-m-b-30"><br><br>17 % of the for all shipping estimate.</span>
                    <span class="gl-text"><br><br>Note: There are some countries where free shipping is available otherwise our flat rate charges or country delivery charges will be apply.</span>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 u-s-m-b-30">
                  <div class="f-cart__pad-box">
                    <h1 class="gl-h1">NOTE</h1>
                    <span class="gl-text u-s-m-b-30">Add Special Note About Your Product</span>
                    <div>
                      <label for="f-cart-note"></label><textarea style="height:120px;" class="text-area text-area--primary-style" id="f-cart-note"></textarea>
                    </div>
                  </div>
                </div>
                <div id='cartTotal' class="col-lg-4 col-md-6 u-s-m-b-30 ">
                  <div class="f-cart__pad-box">
                    <div class="u-s-m-b-30">
                      <table class="f-cart__table">
                        <tbody>
                          <tr>
                            <td>SUBTOTAL</td>
                            <td>${{total_amount|floatformat:2}}</td>
                          </tr>
                          <tr>
                            <td>SHIPPING</td>
                            <td>${{charge|floatformat:2}}</td>
                          </tr>
                          <tr>
                            <td>TAX</td>
                            <td>${{gst|floatformat:2}}</td>
                          </tr>
                          <tr>
                            <td>GRAND TOTAL</td>
                            <td>${{grandtotal|floatformat:2}}</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <div>
                      <button class="btn btn--e-brand-b-2" type="submit"> PROCEED TO CHECKOUT</button>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!--====== End - Section Content ======-->
  </div>
  <!--====== End - Section 3 ======-->
</div>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script>
  $(document).ready(function(){
      // Get value on button click and show alert
      $(".ajax_clicked").on('click',function(e){
          e.preventDefault()
          const product_id = $(this).attr('id')
          const product_qty = $(`input[name="jquery_qty_${product_id}"]`).val()
          const _csrf = $('input[name="csrfmiddlewaretoken"]').val()
          const _href = $(`#href_get_${product_id}`).attr('href')
          //var total = 0;
          //const total = $(`.get_price_${product_id}`).text().slice(2)
          //alert(total)
  
          //alert(product_id+' '+product_qty +'\n'+_href);
  
          $.ajax({
          url: _href , 
          type: "POST",
          data: {
              'csrfmiddlewaretoken': _csrf,
              'product_pk' : product_id,
              'product_qty' : parseInt(product_qty),
              },
          success: function (result) {
              //alert('Quantity Updated :- ' + result.qty)
              $("#cartTotal").load(location.href + " #cartTotal > *");
          
          },
          error: function (err) {
          }
          });
  
      });
  
  });
  
  //$(document).ready(function(){
  //    var price_get = $(`#for_loop_counter_${product_id}`).val()
  //    var total = $(`.get_price_${product_id}`).text().slice(2)
  //    console.log(total)
  //    console.log(price_get)
  //});
  
</script>
{% endblock content %}
<!--====== End - App Content ======-->