cart/urls.py
from django.urls import path,include
from cart import views


app_name ='cart'

urlpatterns = [
    path('',views.cart,name = 'cart'),
    path('add/cart/<int:pk>/',views.addCart,name='addCart'),
    path('update/cart/<int:pk>/',views.updateCart,name='updateCart'),
    path('remove-form-wishlist-to-cart/<int:pk>/',views.wish_to_cart,name='wish_to_cart'),
    path('remove/cart/<int:pk>/',views.removeCart,name = 'removeCart'),
    path('remove-all-cart/',views.removeAllCart,name = 'removeAllCart'),



]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views
from accounting import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/login/', views.redirectToLogin, name='login'),
    path('admin/', admin.site.urls),
    path('account/', include('accounting.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/signup/', TemplateView.as_view(template_name="account/customer/signup.html")),

    path('', include('home.urls')),
    path('profile/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    path('blog/', include('blog.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('faq/', include('faq.urls')),
    path('about/', include('about_us.urls')),
    path('contact/', include('contact.urls')),
    path('checkout/', include('checkout.urls')),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name = "registration/password_reset.html"),name='lost_password'),
    path('accounts/', include('django.contrib.auth.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path,include
from faq import views

app_name ='faq'


urlpatterns = [
        path('',views.faq,name='faq'),

]

home/urls.py
from django.urls import path,include
from home import views

app_name ='home'


urlpatterns = [
    path('', views.homepage,name = 'home'),
    path('product-detail/<int:pk>/',views.product_detail,name= 'product_detail'),
    path('shop-grid-left/<int:pk>/', views.shop_grid_left,name = 'shop_grid_left'),
    path('shop-grid-left/', views.all_shop_grid_left,name = 'all_shop_grid_left'),
    path('shop-grid-left-sub-category/<int:pk>/', views.shop_grid_left_sub_category,name = 'shop_grid_left_sub_category'),
    path('shop-grid-left-category/<int:pk>/', views.shop_grid_left_category,name = 'shop_grid_left_category'),

]

wishlist/urls.py
from django.urls import path,include
from wishlist import views


app_name ='wishlist'

urlpatterns = [
        path('',views.wishlist,name='wishlist'),
        path('add/wishlist/<int:pk>/',views.addWish,name='addWish'),
        path('remove/wishlist/<int:pk>/',views.removeWish,name = 'removeWish'),
        path('remove-all-wish/',views.removeAllWish,name = 'removeAllWish'),


]

wishlist/models.py
from django.db import models
from accounting.models import User
from dashboard.models import Address,DefaultAddress,AddressType,Country,State,City,Area,Pincode
from home.models import ProductMainCategory,ProductSubCategory,ProductCategory,MainProduct,Product,Product_SubInformation,Information,ProductTags,ProductPolicy,AvailablePolicies,ProductReview,Product_SubInformation,Information
from datetime import datetime
from datetime import date
# Create your models here.



class ProductWishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    Product_wishlist_Upload_Date = models.DateTimeField(default = datetime.now())
    def __str__(self):
        return self.product.Product_Title

#  

wishlist/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.core import serializers
from accounting.models import User
from dashboard.models import Address,DefaultAddress,AddressType,Country,State,City,Area,Pincode
from home.models import ProductMainCategory,ProductSubCategory,ProductCategory,MainProduct,Product,Product_SubInformation,Information,ProductTags,ProductPolicy,AvailablePolicies,ProductReview,Product_SubInformation,Information
from home.forms import ProductUploadForm
from wishlist.models import ProductWishList
from django.contrib import messages
from django.core.files.storage import FileSystemStorage 
# from django.contrib.auth.decorators import login_required


# Create your views here.
# @login_required
def wishlist(request):
    # print(ProductWishList.objects.filter(user = request.user))
    try:
        user_wishlist = ProductWishList.objects.filter(user = request.user)
    except:
        user_wishlist ={}
    
    context = {
            'ProductWishList' : user_wishlist,
        }

    return render(request,'wishlist/wishlist.html',context)
    

def addWish(request,pk):
    if request.method == 'POST':
        # print(request.POST.get('product_pk'))
        
        # ProductWishList.objects.create(
        #     user = User.objects.get(pk = request.user.pk),
        #     product = Product.objects.get(pk = request.POST.get('product_pk'))
        # ).save()
        # print(pk)

        p, created = ProductWishList.objects.get_or_create(
            user = User.objects.get(pk = request.user.pk),
            product = Product.objects.get(pk = pk)
        )

        if created:
            return JsonResponse({'res':'Product is Added to Wishlist'})
        else:
            return JsonResponse({'res':'Product is Exist to Wishlist'})

    return render(request,'wishlist/wishlist.html')


def removeWish(request,pk):
    print(pk)
    # if ProductWishList == request.user:
    ProductWishList.objects.filter(pk=pk).delete()
    return redirect('wishlist:wishlist')
    # else:
        # HttpResponse('please login with the correct user and try again')
    # return render(request,'wishlist/wishlist.html')

def removeAllWish(request):
    try:
        ProductWishList.objects.filter(user = User.objects.get(pk = request.user.pk)).delete()
    except:
        messages.error(request,f'login first and try it again..' )
    return redirect('wishlist:wishlist')

wishlist/templates/wishlist/wishlist.html
{% extends 'base.html' %}
{% load static %}
<!--====== App Content ======-->
{% block content %}
{% csrf_token %}
<div class="app-content">
  <!--====== Section 1 ======-->
  <div class="u-s-p-y-60">
    <!--====== Section Content ======-->
    <div class="section__content">
      <div class="container">
        <div class="breadcrumb">
          <div class="breadcrumb__wrap">
            <ul class="breadcrumb__list">
              <li class="has-separator">
                <a href="{% url 'home:home' %}">Home</a>
              </li>
              <li class="is-marked">
                <a href="{% url 'wishlist:wishlist' %}">Wishlist</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--====== End - Section 1 ======-->
  <!--====== Section 2 ======-->
  <div class="u-s-p-b-60">
    <!--====== Section Intro ======-->
    <div class="section__intro u-s-m-b-60">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="section__text-wrap">
              <h1 class="section__heading u-c-secondary">Wishlist</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--====== End - Section Intro ======-->
    <!--====== Section Content ======-->
    <div class="section__content">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12">
            <!--====== Wishlist Product ======-->
            {% for ProductWishList in ProductWishList %}
            {% if request.user == ProductWishList.user %}
            {% comment %} {{ProductWishList}} {% endcomment %}
            <div class="w-r u-s-m-b-30">
              <div class="w-r__container">
                <div class="w-r__wrap-1">
                  <div class="w-r__img-wrap">
                    <img class="u-img-fluid" style="height:120px;" src="{{ProductWishList.product.Product_Img_1.url}}" alt="">
                  </div>
                  <div class="w-r__info">
                    <span class="w-r__name">
                    <a href="{% url 'home:product_detail' ProductWishList.product.pk %}">{{ProductWishList.product.Product_Title|slice:'0:30'}} ...</a></span>
                    <span class="w-r__category">
                    <a href="{% url 'home:shop_grid_left' ProductWishList.product.maincategory.pk %}">{{ProductWishList.product.maincategory|title}}</a></span>
                    <span class="w-r__price">${{ProductWishList.product.Product_Price|floatformat:2}}
                    <span class="w-r__discount">${{ProductWishList.product.Product_Cutoff_Price|floatformat:2}}</span></span>
                  </div>
                </div>
                <div class="w-r__wrap-2">
                  {% if request.user.UserType == 'customer' %}
                  <a href="{% url 'cart:wish_to_cart' ProductWishList.product.pk %}"  class="w-r__link btn--e-brand-b-2" data-modal="modal" data-modal-id="#add-to-cart">ADD TO CART</a>
                  <input name="product_qty" style="display:none;" value="1">
                  {% endif %}
                  <a class="w-r__link btn--e-transparent-platinum-b-2" href="{% url 'home:product_detail' ProductWishList.product.pk %}">VIEW</a>
                  <a class="w-r__link btn--e-transparent-platinum-b-2" href="{% url 'wishlist:removeWish' ProductWishList.pk %}">REMOVE</a>
                </div>
              </div>
            </div>
            {% endif %}
            {% endfor ProductWishList %}
            <!--====== End - Wishlist Product ======-->
            <!--====== Wishlist Product ======-->
            {% comment %} 
            <div class="w-r u-s-m-b-30">
              <div class="w-r__container">
                <div class="w-r__wrap-1">
                  <div class="w-r__img-wrap">
                    <img class="u-img-fluid" src="{% static 'images/product/men/product8.jpg' %}" alt="">
                  </div>
                  <div class="w-r__info">
                    <span class="w-r__name">
                    <a href="product-detail.html">New Fashion D Nice Elegant</a></span>
                    <span class="w-r__category">
                    <a href="shop-side-version-2.html">Men Clothing</a></span>
                    <span class="w-r__price">$125.00
                    <span class="w-r__discount">$160.00</span></span>
                  </div>
                </div>
                <div class="w-r__wrap-2">
                  <a class="w-r__link btn--e-brand-b-2" data-modal="modal" data-modal-id="#add-to-cart">ADD TO CART</a>
                  <a class="w-r__link btn--e-transparent-platinum-b-2" href="product-detail.html">VIEW</a>
                  <a class="w-r__link btn--e-transparent-platinum-b-2" href="#">REMOVE</a>
                </div>
              </div>
            </div>
            {% endcomment %}
            <!--====== End - Wishlist Product ======-->
          </div>
          <div class="col-lg-12">
            <div class="route-box">
              <div class="route-box__g">
                <a class="route-box__link" href="{% url 'home:all_shop_grid_left' %}"><i class="fas fa-long-arrow-alt-left"></i>
                <span>CONTINUE SHOPPING</span></a>
              </div>
              <div class="route-box__g">
                <a class="route-box__link" href="{% url 'wishlist:removeAllWish' %}"><i class="fas fa-trash"></i>
                <span>CLEAR WISHLIST</span></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--====== End - Section Content ======-->
  </div>
  <!--====== End - Section 2 ======-->
</div>
{% endblock content %}
<!--====== End - App Content ======-->