accounting/urls.py
from django.urls import path,include
from accounting import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

app_name = 'account'

urlpatterns = [
    path('', views.account_information, name = 'account_information'),

    path('signup',views.signup,name = 'signup'),
    path('signup-seller',views.signup_seller,name = 'signup_seller'),
    path('signin/',views.signin,name = 'signin'),
    path('logout/',views.logout_page,name = 'logout'),
    path('lost-password',views.lost_password,name = 'lost_password'),

]



    # path('accounts/', include('allauth.urls')),
    # path('logout', LogoutView.as_view()),

dashboard/urls.py
from django.urls import path,include
from dashboard import views

app_name ='profile'

urlpatterns = [
    path('', views.dashboard, name = 'manage_myaccount'),
    path('my-profile',views.myprofile,name = 'myprofile'),
    path('edit-profile',views.edit_profile,name ='edit_profile'),


    path('address-book/',views.address_book,name='address_book'),

    path('edit-address/<int:pk>/',views.edit_address,name='edit_address'),


    path('edit-default-address/',views.edit_default_address, name='edit_default_address'),
    path('add-new-address',views.add_new_address,name='add_new_address'),
    path('track-order',views.track_order,name='track_order'),
    path('my-orders',views.my_orders,name='my_orders'),
    path('manage-orders',views.manage_orders,name='manage_orders'),
    path('my-payment-option',views.my_payment_option,name='my_payment_option'),
    path('track-and-Cancel',views.track_ordMy_Returns_and_Cancellationser,name='trackand_Cancel'),


# all product controles
    path('all-product', views.all_product, name='all_product'),
    path('product-upload', views.product_upload, name='product_upload'), #add product
    path('product-edit/', views.product_edit,name= 'product_edit'),
    path('product-edit-one/<int:pk>/',views.product_edit_one,name='product_edit_one'),
    path('product-edit-delete/<int:pk>/',views.product_edit_delete,name= 'product_edit_delete'),
    path('product-view', views.product_view,name= 'product_view'),
    path('product-view-one/<int:pk>/', views.product_view_one,name= 'product_view_one'),

    
# ajax products categories
    path('get-sub-cat',views.get_sub_cat,name = 'get_sub_cat'),
    path('get-cat',views.get_cat,name = 'get_cat'),
    path('main-product',views.main_product,name = 'main_product'),

# ajax countries
    path('get-state', views.get_state, name = 'get_state'),
    path('get-city', views.get_city, name = 'get_city'),
    path('get-area', views.get_area, name = 'get_area'),
    path('get-pincode', views.get_pincode, name = 'get_pincode'),

]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from django.contrib.auth import views as auth_views
from accounting import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/login/', views.redirectToLogin, name='login'),
    path('admin/', admin.site.urls),
    path('account/', include('accounting.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/signup/', TemplateView.as_view(template_name="account/customer/signup.html")),

    path('', include('home.urls')),
    path('profile/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    path('blog/', include('blog.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('faq/', include('faq.urls')),
    path('about/', include('about_us.urls')),
    path('contact/', include('contact.urls')),
    path('checkout/', include('checkout.urls')),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name = "registration/password_reset.html"),name='lost_password'),
    path('accounts/', include('django.contrib.auth.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path,include
from faq import views

app_name ='faq'


urlpatterns = [
        path('',views.faq,name='faq'),

]

home/urls.py
from django.urls import path,include
from home import views

app_name ='home'


urlpatterns = [
    path('', views.homepage,name = 'home'),
    path('product-detail/<int:pk>/',views.product_detail,name= 'product_detail'),
    path('shop-grid-left/<int:pk>/', views.shop_grid_left,name = 'shop_grid_left'),
    path('shop-grid-left/', views.all_shop_grid_left,name = 'all_shop_grid_left'),
    path('shop-grid-left-sub-category/<int:pk>/', views.shop_grid_left_sub_category,name = 'shop_grid_left_sub_category'),
    path('shop-grid-left-category/<int:pk>/', views.shop_grid_left_category,name = 'shop_grid_left_category'),

]

dashboard/models.py
from django.db import models
from accounting.models import User
from django.urls import reverse

# Create your models here.

class AddressType(models.Model):
    Types = models.CharField(default='home',max_length=20,choices=(('home','home'),('office','office')))

    def __str__(self):
        return self.Types

class Country(models.Model):
    CountryName = models.CharField(max_length=256)

    def __str__(self):
        return self.CountryName

class State(models.Model):
    StateName = models.CharField(max_length=40)
    country = models.ForeignKey(Country,on_delete=models.CASCADE)

    def __str__(self):
        return self.StateName

class City(models.Model):
    CityName = models.CharField(max_length=40)
    state = models.ForeignKey(State,on_delete=models.CASCADE)

    def __str__(self):
        return self.CityName

class Area(models.Model):
    AreaName = models.CharField(max_length=40)
    city = models.ForeignKey(City,on_delete=models.CASCADE)

    def __str__(self):
        return self.AreaName


class Pincode(models.Model):
    PincodeArea = models.CharField(max_length=40)
    area = models.ForeignKey(Area,on_delete=models.CASCADE)

    def __str__(self):
        return self.PincodeArea

class Address(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    FirstName = models.CharField(max_length=256)
    LastName = models.CharField(max_length=256)
    Contact = models.IntegerField()
    address_type = models.ForeignKey(AddressType,on_delete=models.CASCADE)# 
    StreetAddress = models.CharField(max_length=256)
    area = models.ForeignKey(Area,on_delete=models.CASCADE)#
    city = models.ForeignKey(City,on_delete=models.CASCADE)
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    country = models.ForeignKey(Country,on_delete=models.CASCADE)
    pincode = models.ForeignKey(Pincode,on_delete=models.CASCADE)


    # def get_absolute_url(self):
    #     return reverse("profile:editAddress", kwargs={"pk": self.pk})

    def __str__(self):
        return self.user.first_name +' '+self.user.last_name +' -> '+ self.StreetAddress

class DefaultAddress(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    dafault_address = models.ForeignKey(Address, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name +' '+self.user.last_name +' -> '+ self.dafault_address.StreetAddress








    

dashboard/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.core import serializers
from accounting.models import User
from dashboard.models import Address,DefaultAddress,AddressType,Country,State,City,Area,Pincode
from home.models import ProductMainCategory,ProductSubCategory,ProductCategory,MainProduct,Product,Product_SubInformation,Information,ProductTags,ProductPolicy,AvailablePolicies,ProductReview,Product_SubInformation,Information
from home.forms import ProductUploadForm
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required

# from django.contrib.auth import get_user_model   #to enter user datta in user models 
# User = get_user_model() 


# Create your views here.
# @login_required
def dashboard(request):
    try :
        user_default_address = DefaultAddress.objects.get(user= request.user)
    except:
        user_default_address = 'add default address for shifting'

    context =  {
            'user_detail' : request.user,
            # 'user_default_address' : DefaultAddress.objects.get(user= request.user),
            'user_default_address': user_default_address
    }
    return render(request,'dashboard/dashboard.html',context)


def myprofile(request):
    context =  {
            'user_detail' : request.user
    }

    return render(request,'dashboard/dash-my-profile.html',context)

def edit_profile(request):
    
    if request.method == 'POST':
        user_data = User.objects.filter(pk = request.user.id).update(first_name = request.POST.get('add_fname'),
                                                                 last_name = request.POST.get('add_lname'), 
                                                                 Dob = request.POST.get('date_of_birth'), 
                                                                 Gender = request.POST.get('add_gender'), 
                                                                 email = request.POST.get('add_email'), 
                                                                 Mobile = request.POST.get('add_contact'))
        messages.success(request,f'your profile is updated')
        return redirect('profile:myprofile')

    context =  {
            'user_detail' : request.user
        }
    return render(request,'dashboard/dash-edit-profile.html',context)


def address_book(request):
    try:
        user_detail = request.user
        user_addresses = Address.objects.filter(user = request.user)
    except:
        user_detail = {}
        user_addresses = {}

    context =  {
            'user_detail' : user_detail,
            'user_addresses' : user_addresses,
    }
    return render (request,'dashboard/dash-address-book.html',context)


def edit_address(request,pk):
    if request.method == 'POST':
        Address.objects.filter(pk=pk).update(
                                                user = request.user,
                                                FirstName = request.POST.get('FirstName'),
                                                LastName = request.POST.get('LastName'),
                                                Contact = request.POST.get('Contact'),
                                                StreetAddress = request.POST.get('Street_Address'),
                                                country = request.POST.get('Country'),
                                                state = request.POST.get('State'),
                                                area = request.POST.get('Area'),
                                                address_type = request.POST.get('Address_Type'),
                                                city = request.POST.get('City'),
                                                pincode = request.POST.get('pin_Code'),
                                            )
        messages.success(request,f'your address profile is currently updated')


    context =  {
            'user_detail' : request.user,
            'user_addresses' : Address.objects.filter(pk=pk),
            'countrys' : Country.objects.all(),
            'states' : State.objects.all() , 
            'citys' : City.objects.all(),
            'areas' : Area.objects.all(),
            'pincodes' : Pincode.objects.all(),
            'address_types' : AddressType.objects.all(),
    }
    return render (request,'dashboard/dash-address-edit.html',context)


def edit_default_address(request):
    if request.method == 'POST':
        used_deflt_id = request.POST.get('default_address')
        user_set = Address.objects.get(pk = used_deflt_id)
        try:
            DefaultAddress.objects.filter(user=request.user).update(dafault_address=user_set)
            print("try")

        except:
            DefaultAddress.objects.create(user=request.user,dafault_address=user_set)
            print("except")

    try :
        user_detail = request.user
        user_addresses = Address.objects.filter(user=request.user)
        user_default_address =DefaultAddress.objects.get(user=request.user)

    except:
        user_detail = {}
        user_addresses ={} 
        user_default_address = {}
        messages.error(request,f'Please Login First and try it Again ')

        

    context =  {
                'user_detail' : user_detail,
                'user_addresses' : user_addresses,
                'user_default_address' : user_default_address,
        }
    return render(request,'dashboard/dash-address-make-default.html',context)




def add_new_address(request):
    if request.method == 'POST':
        obj = Address.objects.create(
                                    user = request.user,
                                    FirstName = request.POST.get('FirstName'),
                                    LastName = request.POST.get('LastName'),
                                    Contact = request.POST.get('New_Contact'),
                                    StreetAddress = request.POST.get('New_Street_Address'),
                                    country = Country.objects.get(pk= request.POST.get('New_country')),
                                    state = State.objects.get(pk = request.POST.get('New_State')),
                                    area = Area.objects.get(pk= request.POST.get('New_Area')),
                                    address_type = AddressType.objects.get(pk=request.POST.get('New_Address_Type')),
                                    city = City.objects.get(pk=request.POST.get('New_City')),
                                    pincode =Pincode.objects.get(pk= request.POST.get('New_Pincode')),
                                    )
        obj.save()
        messages.success(request,f'your address profile created')
        print(obj.pk)

        try:
            efault_user_obj = DefaultAddress.objects.get(user = request.user)
        except:
            deflt_obj = DefaultAddress.objects.create(user= request.user,dafault_address = Address.objects.get(pk=obj.pk))
            deflt_obj.save()
            

    context =  {
            'user_detail' : request.user,
            'countrys' : Country.objects.all(),
            'states' : State.objects.all() , 
            'citys' : City.objects.all(),
            'areas' : Area.objects.all(),
            'pincodes' : Pincode.objects.all(),
            'address_types' : AddressType.objects.all(),
    }
    return render(request,'dashboard/dash-address-add.html',context)

def track_order(request):
    context =  {
            'user_detail' : request.user
    }
    return render (request,'dashboard/dash-track-order.html',context)

def my_orders(request):
    context =  {
            'user_detail' : request.user
    }
    return render (request,'dashboard/dash-my-order.html',context)

def manage_orders(request):
    context =  {
            'user_detail' : request.user
    }
    return render(request,'dashboard/dash-manage-order.html',context)

def my_payment_option(request):
    context =  {
            'user_detail' : request.user
    }
    return render (request,'dashboard/dash-payment-option.html',context)

def track_ordMy_Returns_and_Cancellationser(request):
    context =  {
            'user_detail' : request.user
    }
    return render (request,'dashboard/dash-cancellation.html',context)


def all_product(request):
    context =  {
            'user_detail' : request.user
    }
    return render(request,'dashboard/dash-product-index.html',context)


def product_upload(request):
    context =  {
            'user_detail' : request.user,
            'ProductMainCategory' : ProductMainCategory.objects.all(),
            'ProductSubCategory' : ProductSubCategory.objects.all(),
            'ProductCategory' : ProductCategory.objects.all(),
            'MainProduct' : MainProduct.objects.all(),
            'AvailablePolicies' : AvailablePolicies.objects.all(), 
        }
    
    if request.method == 'POST':

        # this is to pass the form and recive the request.post of product
        form = ProductUploadForm(request.POST,request.FILES)
        if form.is_valid():
            form_obj = form.save(commit=False)
            form_obj.user = User.objects.get(pk=request.user.pk)
            form_obj.save()


            # this is the code of product selected policies
            policy_id = request.POST.get('allpolicy')
            policy_id = policy_id.split(',')
            select_name_of_policy =[]
            for policy in policy_id:
                policy = int(policy)-1
                name = AvailablePolicies.objects.all()
                select_name_of_policy.append(name[policy])  
                print(select_name_of_policy)
            
            for add_policy in select_name_of_policy:
                add_q = str(add_policy)
                print(add_q)
                policy_obj = ProductPolicy.objects.create(product = Product.objects.get(pk= form_obj.pk),

dashboard/templates/dashboard/dash-address-book.html
{% extends 'base.html' %}
{% load static %}
<!--====== App Content ======-->
{% block content %}
<div class="app-content">
  <!--====== Section 1 ======-->
  <div class="u-s-p-y-60">
    <!--====== Section Content ======-->
    <div class="section__content">
      <div class="container">
        <div class="breadcrumb">
          <div class="breadcrumb__wrap">
            <ul class="breadcrumb__list">
              <li class="has-separator">
                <a href="{% url 'home:home' %}">Home</a>
              </li>
              <li class="is-marked">
                <a href="{% url 'profile:address_book' %}">My Account</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--====== End - Section 1 ======-->
  <!--====== Section 2 ======-->
  <div class="u-s-p-b-60">
    <!--====== Section Content ======-->
    <div class="section__content">
      <div class="dash">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-12">
              <!--====== Dashboard Features ======-->
              <div class="dash__box dash__box--bg-white dash__box--shadow u-s-m-b-30">
                <div class="dash__pad-1">
                  <span class="dash__text u-s-m-b-16">Hello, {{user_detail.first_name}} {{user_detail.last_name}}</span>
                  <ul class="dash__f-list">
                    {% if user_detail.UserType == 'customer' %} 
                    <li>
                      <a href="{% url 'profile:manage_myaccount' %}">Manage My Account</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:myprofile' %}">My Profile</a>
                    </li>
                    <li>
                      <a class="dash-active" href="{% url 'profile:address_book' %}">Address Book</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:track_order' %}">Track Order</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:my_orders' %}">My Orders</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:my_payment_option' %}">My Payment Options</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:trackand_Cancel' %}">My Returns & Cancellations</a>
                    </li>
                    {% elif user_detail.UserType == 'seller' %}
                    <li>
                      <a href="{% url 'profile:manage_myaccount' %}">Manage My Account</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:myprofile' %}">My Profile</a>
                    </li>
                    <li>
                      <a class="dash-active" href="{% url 'profile:address_book' %}">Address Book</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:track_order' %}">Manage Order</a>
                    </li>
                    <li>
                      <a href="{% url 'profile:all_product' %}">Your Products Detail</a>
                    </li>
                    {% else %}
                    <h3>Please <a href="{% url 'account:signin' %}" >SIGN IN </a></h3>
                    {% endif %}
                  </ul>
                </div>
              </div>
              <div class="dash__box dash__box--bg-white dash__box--shadow dash__box--w">
                <div class="dash__pad-1">
                  <ul class="dash__w-list">
                    {% if user_detail.UserType == 'customer' %}
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-1"><i class="fas fa-cart-arrow-down"></i></span>
                        <span class="dash__w-text">4</span>
                        <span class="dash__w-name">Orders Placed</span>
                      </div>
                    </li>
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-2"><i class="fas fa-times"></i></span>
                        <span class="dash__w-text">0</span>
                        <span class="dash__w-name">Cancel Orders</span>
                      </div>
                    </li>
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-3"><i class="far fa-heart"></i></span>
                        <span class="dash__w-text">0</span>
                        <span class="dash__w-name">Wishlist</span>
                      </div>
                    </li>
                    {% elif user_detail.UserType == 'seller' %}
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-1"><i class="fas fa-cart-arrow-down"></i></span>
                        <span class="dash__w-text">4</span>
                        <span class="dash__w-name">Pending Orders</span>
                      </div>
                    </li>
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-2"><i class="fas fa-times"></i></span>
                        <span class="dash__w-text">0</span>
                        <span class="dash__w-name">Cancel Orders</span>
                      </div>
                    </li>
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-3"><i class="fas fa-cart-arrow-down"></i></span>
                        <span class="dash__w-text">0</span>
                        <span class="dash__w-name">Complete Orders</span>
                      </div>
                    </li>
                    {% else %}
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-1"><i class="fas fa-cart-arrow-down"></i></span>
                        <span class="dash__w-text">0</span>
                        <span class="dash__w-name">Orders Placed</span>
                      </div>
                    </li>
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-2"><i class="fas fa-times"></i></span>
                        <span class="dash__w-text">0</span>
                        <span class="dash__w-name">Cancel Orders</span>
                      </div>
                    </li>
                    <li>
                      <div class="dash__w-wrap">
                        <span class="dash__w-icon dash__w-icon-style-3"><i class="far fa-heart"></i></span>
                        <span class="dash__w-text">0</span>
                        <span class="dash__w-name">Wishlist</span>
                      </div>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
              <!--====== End - Dashboard Features ======-->
            </div>
            <div class="col-lg-9 col-md-12">
              <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white u-s-m-b-30">
                <div class="dash__pad-2">
                  <div class="dash__address-header">
                    <h1 class="dash__h1">{% if user_detail.UserType == 'customer' %}Address Book{% elif user_detail.UserType == 'seller' %}Seller Address Book{% else %}Address Book{% endif %}</h1>
                    <div>
                      <span class="dash__link dash__link--black">
                      <a href="{% url 'profile:edit_default_address' %}">{% if user_detail.UserType == 'customer' %}Make default shipping address{% elif user_detail.UserType == 'seller' %}Make default pickup address{% else %}{% endif %}</a></span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="dash__box dash__box--shadow dash__box--bg-white dash__box--radius u-s-m-b-30">
                <div class="dash__table-2-wrap gl-scroll">
                  <table class="dash__table-2">
                    <thead>
                      <tr>
                        <th>Action</th>
                        <th>Full Name</th>
                        <th>Address</th>
                        <th>Region</th>
                        <th>Phone Number</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for user_address in user_addresses %}
                      <tr>
                        <td>
                          <a class="address-book-edit btn--e-transparent-platinum-b-2" href="{% url 'profile:edit_address' user_address.pk %}">Edit</a>
                        </td>
                        <td>{{user_address.FirstName}} {{user_address.LastName}} {{user_address.pk}}</td>
                        <td>{{user_address.StreetAddress}} {{user_address.state}}-{{user_address.pincode}} {{user_address.country}}</td>
                        <td>{{user_address.area}} {{user_address.city}} {{user_address.state}}-{{user_address.pincode}} {{user_address.country}}</td>
                        <td>(+91) {{user_address.Contact}}</td>
                        <td>
                          {% if user_address.default_address_status == 'true'  %}
                          <div class="gl-text">Default Shipping Address</div>
                          <div class="gl-text">Default Billing Address</div>
                          {% else %}
                          <div class="gl-text">
                            Click to 
                            <a href="{% url 'profile:edit_default_address' %}">
                              Make default 
                          </div>
                          <div class="gl-text"> Shipping Address</a> given above</div>
                          {% endif %}
                        </td>
                      </tr>
                      {% endfor %}
                      {% comment %} 
                      <tr>
                        <td>
                          <a class="address-book-edit btn--e-transparent-platinum-b-2" href="#">Edit</a>
                        </td>
                        <td>Doe John</td>
                        <td>1484 Abner Road</td>
                        <td>Eau Claire WI - Wisconsin</td>
                        <td>(+0) 7154419563</td>
                        <td></td>
                      </tr>
                      {% endcomment %}
                    </tbody>
                  </table>
                </div>
              </div>
              {% if request.user.is_authenticated %}
              <div>
                <a class="dash__custom-link btn--e-brand-b-2" href="{% url 'profile:add_new_address' %}"><i class="fas fa-plus u-s-m-r-8"></i>
                <span>Add New Address</span></a>
              </div>
              {% else %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--====== End - Section Content ======-->
  </div>
  <!--====== End - Section 2 ======-->
</div>
{% endblock content %}
<!--====== End - App Content ======-->